"""
User model for MongoDB.
Represents user accounts with authentication credentials.
"""
from datetime import datetime
from typing import Optional
from bson import ObjectId


class UserModel:
    """
    User document structure for MongoDB.
    
    Fields:
        _id: ObjectId (auto-generated by MongoDB)
        email: Unique email address
        hashed_password: Bcrypt hashed password
        full_name: User's display name
        created_at: Account creation timestamp
        is_active: Account status flag
    """
    
    @staticmethod
    def create_document(
        email: str,
        hashed_password: str,
        full_name: str
    ) -> dict:
        """
        Create a new user document for insertion into MongoDB.
        
        Args:
            email: User's email address
            hashed_password: Bcrypt hashed password
            full_name: User's full name
            
        Returns:
            Dictionary representing the user document
        """
        return {
            "email": email.lower(),  # Store emails in lowercase for consistency
            "hashed_password": hashed_password,
            "full_name": full_name,
            "created_at": datetime.utcnow(),
            "is_active": True
        }
